-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION graphql_public.graphql(
	"operationName" text DEFAULT NULL::text,
	query text DEFAULT NULL::text,
	variables jsonb DEFAULT NULL::jsonb,
	extensions jsonb DEFAULT NULL::jsonb)
    RETURNS jsonb
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
    DECLARE
        server_version float;
    BEGIN
        server_version = (SELECT (SPLIT_PART((select version()), ' ', 2))::float);

        IF server_version >= 14 THEN
            RETURN jsonb_build_object(
                'data', null::jsonb,
                'errors', array['pg_graphql extension is not enabled.']
            );
        ELSE
   	        RETURN jsonb_build_object(
                'data', null::jsonb,
                'errors', array['pg_graphql is only available on projects running Postgres 14 onwards.']
            );
        END IF;
    END;
$BODY$;

ALTER FUNCTION graphql_public.graphql(text, text, jsonb, jsonb)
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public.room_member FROM authenticated;
REVOKE ALL ON TABLE public.room_member FROM postgres;
REVOKE ALL ON TABLE public.room_member FROM service_role;
GRANT ALL ON TABLE public.room_member TO authenticated;

GRANT ALL ON TABLE public.room_member TO postgres;

GRANT ALL ON TABLE public.room_member TO service_role;

REVOKE ALL ON TABLE public.room FROM authenticated;
REVOKE ALL ON TABLE public.room FROM postgres;
REVOKE ALL ON TABLE public.room FROM service_role;
GRANT ALL ON TABLE public.room TO authenticated;

GRANT ALL ON TABLE public.room TO postgres;

GRANT ALL ON TABLE public.room TO service_role;

REVOKE ALL ON TABLE public.room_member_invite FROM authenticated;
REVOKE ALL ON TABLE public.room_member_invite FROM postgres;
REVOKE ALL ON TABLE public.room_member_invite FROM service_role;
GRANT ALL ON TABLE public.room_member_invite TO authenticated;

GRANT ALL ON TABLE public.room_member_invite TO postgres;

GRANT ALL ON TABLE public.room_member_invite TO service_role;

REVOKE ALL ON TABLE public.room_message FROM authenticated;
REVOKE ALL ON TABLE public.room_message FROM postgres;
REVOKE ALL ON TABLE public.room_message FROM service_role;
GRANT ALL ON TABLE public.room_message TO authenticated;

GRANT ALL ON TABLE public.room_message TO postgres;

GRANT ALL ON TABLE public.room_message TO service_role;
